server:
  port: 8088

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost/marketplace_order
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
